---
#######################################################################################################################################################################################################################
# Executing commands without the anka plugin enabled WILL EXECUTE ON THE HOST MACHINE AND COULD RUIN THEM. Please ensure you've set the chef/anka plugin and tested that it's executing your commands inside of the VM!
#######################################################################################################################################################################################################################
# You can look for problems using yamllint: brew install yamllint
# Artifact storage is available through root::nas tags; mounted NAS located in /Network/NAS
env:
  ANKA_MOJAVE_IMAGE_NAME: base-10.14.4_6C_16G_30G
  ANKA_MOJAVE_IMAGE_TAG: fresh-nas
  ANKA_WORKDIR: /data/job

steps:

  - trigger: "mac-anka-fleet"
    label: ":anka: Ensure Anka Template Tag Exists"
    branches: "mac-anka-fleet"
    async: false
    build:
      branch: "master"
      env:
        REPO: "${BUILDKITE_REPO}"
        REPO_BRANCH: "${BUILDKITE_BRANCH}"
        REPO_DIRECTORY: "scripts" # use . for everything
        CHECKSUM: "scripts/eosio_build*"
        TEMPLATE: "10.14.4_6C_16G_30G"
        TEMPLATE_TAG: "root::git-ssh::nas"
        TAG: "${BUILDKITE_PIPELINE_SLUG}"
        TAG_COMMANDS: "CLONED_REPO_DIR/scripts/eosio_build.sh -y" # CLONED_REPO_DIR is where the repo was cloned into

  - wait

  - label: ":darwin: [Darwin] Mojave Build"
    command:
      - "sudo mkdir /usr/local/Frameworks && sudo chown anka:admin /usr/local/Frameworks"
      - "./scripts/eosio_build.sh -y"
      - "tar -pczf /Network/NAS/MAC_FLEET/BUILDKITE/artifacts/build-$BUILDKITE_BUILD_ID.tar.gz build"
    plugins:
      chef/anka#v0.4.3:
        vm-name: $ANKA_MOJAVE_IMAGE_NAME
        vm-registry-tag: $ANKA_MOJAVE_IMAGE_TAG
        always-pull: "shrink"
        debug: true
    agents:
      - "queue=mac-anka-fleet"
    timeout: 60

  - wait

  - label: ":darwin: Mojave Tests"
    command:
      - "tar -xzf /Network/NAS/MAC_FLEET/BUILDKITE/artifacts/build-$BUILDKITE_BUILD_ID.tar.gz"
      - "cd build && ~/bin/mongod --fork --dbpath ~/data/mongodb -f ~/etc/mongod.conf --logpath ./mongod.log && PATH=$PATH:~/opt/mongodb/bin ctest -j8 -LE _tests --output-on-failure"
    artifact_paths:
      - "build/mongod.log"
      - "build/genesis.json"
      - "build/config.ini"
    agents:
      - "queue=mac-anka-fleet"
    plugins:
      chef/anka#v0.4.3:
        vm-name: $ANKA_MOJAVE_IMAGE_NAME
        vm-registry-tag: $ANKA_MOJAVE_IMAGE_TAG
        workdir: $ANKA_WORKDIR
        # Tests don't need the host "working directory" mounted
        no-volume: true
        always-pull: "shrink"
        debug: true
    timeout: 60