steps:

  - trigger: "ensure-anka-tag"
    label: ":anka: Ensure Anka Template Tag"
    branches: "mac-anka-fleet"
    async: true
    build:
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"