---
env:
  ANKA_IMAGE_NAME: high-sierra
  ANKA_IMAGE_TAG: clean-nas-eosio-v2-3
  ANKA_WORKDIR: /data/job

steps:
  # Executing commands without the anka plugin enabled WILL EXECUTE ON THE HOST MACHINES AND COULD RUIN THEM. Please be sure to test the anka plugin is functional and executes all commands with 'anka run $COMMAND'
  # You can look for problems using yamllint: brew install yamllint
  # Artifact storage is available through clean-nas images; mounted NAS located in /Network/AFP/NAS

  - label: ":darwin: High Sierra Build"
    command:
      #- "sleep 100000"
      - "echo BUILDKITE_CANCEL_GRACE_PERIOD -------------"
      - "echo \$BUILDKITE_CANCEL_GRACE_PERIOD"
      - "cd /data/job && ./scripts/eosio_build.sh -y"
      - "tar -pczf /Network/AFP/NAS/buildkite-artifacts/build-$BUILDKITE_BUILD_ID.tar.gz build"
    plugins:
      chef/anka#v0.4.0:
        vm-name: $ANKA_IMAGE_NAME
        vm-registry-tag: $ANKA_IMAGE_TAG
        always-pull: "shrink"
        cleanup: false
        debug: true
    agents:
      - "role=anka-tester"
    timeout: 60
    # retry:
    #   automatic:
    #     # Agent was lost
    #     - exit_status: -1
    #       limit: 2
    #     # Forced agent shutdown
    #     - exit_status: 255
    #       limit: 2

  - wait

  - label: ":darwin: High Sierra Tests"
    command:
      - "tar -xzf /Network/AFP/NAS/buildkite-artifacts/build-$BUILDKITE_BUILD_ID.tar.gz"
      - "cd build && ~/bin/mongod --fork --dbpath ~/data/mongodb -f ~/etc/mongod.conf --logpath ./mongod.log && PATH=$PATH:~/opt/mongodb/bin ctest -j8 -LE _tests --output-on-failure"
    artifact_paths:
      - "build/mongod.log"
      - "build/genesis.json"
      - "build/config.ini"
    agents:
      - "role=anka-tester"
    plugins:
      chef/anka#v0.4.0:
        vm-name: $ANKA_IMAGE_NAME
        vm-registry-tag: $ANKA_IMAGE_TAG
        workdir: $ANKA_WORKDIR
        no-volume: true
        # Tests don't need the eosio directory mounted from the host
        always-pull: "shrink"
        debug: true
    timeout: 60

  - label: ":darwin: High Sierra NP Tests"
    command:
      - "tar -zxf /Network/AFP/NAS/buildkite-artifacts/build-$BUILDKITE_BUILD_ID.tar.gz"
      - "cd build && ~/bin/mongod --fork --dbpath ~/data/mongodb -f ~/etc/mongod.conf --logpath ./mongod.log && PATH=$PATH:~/opt/mongodb/bin ctest -L nonparallelizable_tests --output-on-failure"
    artifact_paths:
      - "build/mongod.log"
      - "build/genesis.json"
      - "build/config.ini"
    agents:
      - "role=anka-tester"
    plugins:
      chef/anka#v0.4.0:
        vm-name: $ANKA_IMAGE_NAME
        vm-registry-tag: $ANKA_IMAGE_TAG
        workdir: $ANKA_WORKDIR
        no-volume: true
        # Tests don't need the eosio directory mounted from the host
        always-pull: "shrink"
        debug: true
    timeout: 60

# # Cleanup should be a cron that runs daily